extends Node

class_name CardEnums

enum CardRarity {NULL, COMMON, UNCOMMON, RARE, MYTHIC}
enum CardType  {NULL, CREATURE, SORCERY, LAND, PLANESWALKER, ARTIFACT, ENCHANTMENT}
enum CardKeyword {NULL, ARCANE, GOBLIN, HUMAN, MERFOLK, VAMPIRE, ZOMBIE}
enum CardTarget {NULL, SELF, NONE, TARGET_ALL, TARGET_CREATURE, TARGET_HUMAN, TARGET_ZOMBIE, TARGET_PLAYER, ALL, ALL_CREATURES, ALL_LANDS, ALL_PLAYERS}
